### ISSUE TITLE
Badges are not showing in colors.

### ISSUE THREAD

**Issue by jaideepghosh** [jaideepghosh/lumina#11]
The badges are expected to render with colors based on their type, but the colors are missing.

<img width="464" alt="image" src="https://github.com/jaideepghosh/lumina/assets/3909648/d5f76ef7-f142-4091-a834-48b03a828b1f">

**Comment by ashishpetwal** [comment]
Hello Jaideep, I am willing to contribute to this issue. Could you brief me more about it?

**Comment by jaideepghosh** [comment]
Hi @ashishpetwal 
We have a component called [Badges](https://github.com/jaideepghosh/lumina/blob/main/src/components/Badge.tsx),  For demo purpose, we are using it in src/components/Gallery.tsx
```
<Badge message="love" type={BadgeTypes.DANGER} />
```
But the badges are not rendering in the expected way.

**Comment by ashishpetwal** [comment]
Oh! That means the colour is not being rendered when you use type with Danger or something else.

**Comment by ashishpetwal** [comment]
You can assign the issue to me.

**Comment by jaideepghosh** [comment]
Yes, that's the issue. Assigning it to you.

**Comment by ashishpetwal** [comment]
Fine! I'll make sure to get back to you with an update.
