### ISSUE TITLE
Create a simple 404 error page.

### ISSUE THREAD

**Issue by jaideepghosh** [jaideepghosh/lumina#16]
Create a simple 404 error page and make sure to include the default header navigation.

**Comment by markandey1414** [comment]
Hello @jaideepghosh , I would like to work on this issue

**Comment by jaideepghosh** [comment]
@markandey1414 Sure, assigning it to you. All the best.
Please keep it simple, and use tailwindcss only.

**Comment by markandey1414** [comment]
yes sure
